### ISSUE TITLE
Unnecessary condition when creating table 

### ISSUE THREAD

**Issue by abdhalees** [facg3/MWM-Shop_Project#10]
Since in line 3 you're droping the table, you don't have to check if it doesn't exist in line 4.

https://github.com/facg3/MWM-Shop_Project/blob/ed635ae78424fb61b8a6e2ee5c0c38d484307378/src/database/build.sql#L3
https://github.com/facg3/MWM-Shop_Project/blob/ed635ae78424fb61b8a6e2ee5c0c38d484307378/src/database/build.sql#L4

**Comment by MahmoudMH** [comment]
DONE! thanks @abdhalees
