### ISSUE TITLE
multi value columns

### ISSUE THREAD

**Issue by abdhalees** [facg3/MWM-Shop_Project#11]
I like that you have made your research and found how to store arrays in postgres, as for me it's the first time I know it's possible.
but I still think it's not the best way to store multi values in one column, check this issue https://github.com/facg3/Memeology/issues/23 from another project and whats the better way to store multi values.   
https://github.com/facg3/MWM-Shop_Project/blob/ed635ae78424fb61b8a6e2ee5c0c38d484307378/src/database/build.sql#L16

**Comment by MahmoudMH** [comment]
ok ^_^
