### ISSUE TITLE
missing error handling and headers

### ISSUE THREAD

**Issue by abdhalees** [facg3/MWM-Shop_Project#14]
this function is missing: 
1- error handling
2- headers, when you don't specify your headers they will be set by the browser but you don't want to always relay on browsers they aren't always that clever.
https://github.com/facg3/MWM-Shop_Project/blob/ed635ae78424fb61b8a6e2ee5c0c38d484307378/src/handler.js#L20

**Comment by MahmoudMH** [comment]
humm , yub ! on the next project insaallah , it generate some errs
